### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by ghost** [Urinx/Device-9#2]
Hi, Why the widget doesn't appear?

![img_0138](https://cloud.githubusercontent.com/assets/6787484/10418339/e5206766-7057-11e5-9b30-b308d3bd602f.PNG)
![img_0137](https://cloud.githubusercontent.com/assets/6787484/10418340/e5215752-7057-11e5-9d78-1ead7ffa9a82.PNG)

**Comment by Urinx** [comment]
@lubieapki I forget to change the deployment target of the todayextension, and just leave it to the default value(9.1) -_-||...
<img width="693" alt="screen shot 2015-10-12 at 08 15 34" src="https://cloud.githubusercontent.com/assets/5365195/10420101/4e1af164-70bc-11e5-9de0-804faadf8210.png">
